repos:
    - repo: https://github.com/ambv/black
      rev: 23.3.0
      hooks:
          - id: black
            exclude: ^.*\b(migrations)\b.*$
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - repo: https://github.com/hakancelikdev/unimport
      rev: 0.16.0
      hooks:
        - id: unimport
          args:
            - --include-star-import
            - --ignore-init
            - --gitignore
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            exclude: ^.*\b(migrations)\b.*
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            args: [ "--markdown-linebreak-ext=md,markdown" ]
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-ast
          - id: fix-byte-order-marker
          - id: check-merge-conflict
          - id: debug-statements
          - id: detect-private-key
          - id: detect-aws-credentials
            args: [ "--allow-missing-credentials" ]
